/**
 * Diverse RadioTime search queries merged in parallel to approximate a worldwide station catalog.
 * Each query returns up to ~96 stations; deduplication yields thousands of unique `s…` IDs.
 */
export const WORLD_RADIO_SEARCH_SEEDS: readonly string[] = [
  'radio',
  'fm radio',
  'am radio',
  'live radio',
  'internet radio',
  'jazz radio',
  'classical radio',
  'rock radio',
  'pop radio',
  'country radio',
  'hip hop radio',
  'electronic radio',
  'latin radio',
  'reggae radio',
  'blues radio',
  'folk radio',
  'talk radio',
  'news radio',
  'sports radio',
  'christian radio',
  'public radio',
  'college radio',
  'USA radio',
  'United Kingdom radio',
  'Canada radio',
  'Australia radio',
  'New Zealand radio',
  'Ireland radio',
  'Germany radio',
  'France radio',
  'Spain radio',
  'Italy radio',
  'Netherlands radio',
  'Belgium radio',
  'Switzerland radio',
  'Austria radio',
  'Poland radio',
  'Sweden radio',
  'Norway radio',
  'Denmark radio',
  'Finland radio',
  'Russia radio',
  'Ukraine radio',
  'Greece radio',
  'Portugal radio',
  'Brazil radio',
  'Mexico radio',
  'Argentina radio',
  'Chile radio',
  'Colombia radio',
  'Japan radio',
  'South Korea radio',
  'China radio',
  'Taiwan radio',
  'Hong Kong radio',
  'India radio',
  'Pakistan radio',
  'Indonesia radio',
  'Thailand radio',
  'Vietnam radio',
  'Philippines radio',
  'Malaysia radio',
  'Singapore radio',
  'South Africa radio',
  'Nigeria radio',
  'Kenya radio',
  'Egypt radio',
  'Israel radio',
  'Turkey radio',
  'Saudi Arabia radio',
  'UAE radio',
  'BBC',
  'NPR',
  'CBC',
  'ABC radio',
  'European radio',
  'Asian radio',
  'African radio',
  'Latin America radio',
  'Pacific radio',
  'Caribbean radio',
  'London radio',
  'Paris radio',
  'Berlin radio',
  'Tokyo radio',
  'Sydney radio',
  'Toronto radio',
  'New York radio',
  'Los Angeles radio',
  'Chicago radio',
  'Houston radio',
  'Miami radio',
  'Seattle radio',
  'Boston radio',
  'Dublin radio',
  'Madrid radio',
  'Rome radio',
  'Vienna radio',
  'Prague radio',
  'Warsaw radio',
  'Stockholm radio',
  'Oslo radio',
  'Helsinki radio',
  'Lisbon radio',
  'Dubai radio',
  'Mumbai radio',
  'Bangkok radio',
  'Seoul radio',
  'Shanghai radio',
  'Melbourne radio',
  'Auckland radio',
  'Johannesburg radio',
  'Cairo radio',
  'Lagos radio',
  'Buenos Aires radio',
  'São Paulo radio',
  'Mexico City radio',
  'world music radio',
  'local radio',
]
