#Requires -Version 5.1
<#
  Jarvis + Vonage — Cloudflare Tunnel (dual hostname)

  BEFORE FIRST RUN (one-time, opens browser):
    & "C:\Program Files (x86)\cloudflared\cloudflared.exe" tunnel login

  THEN (from repo root):
    .\scripts\setup-cloudflared-jarvis-vonage-tunnel.ps1

  This script:
    - Ensures tunnel "jarvis-vonage" exists
    - Writes %USERPROFILE%\.cloudflared\config.yml:
        voice.yorkiebrown.uk  -> http://127.0.0.1:3339  (Vonage WebSocket bridge)
        jarvis.yorkiebrown.uk -> http://127.0.0.1:5173  (Vite + /api/vonage webhooks)

  OPTIONAL — create DNS records in Cloudflare (domain must be on your account):
    .\scripts\setup-cloudflared-jarvis-vonage-tunnel.ps1 -RouteDns
#>
param(
  [string] $Cloudflared = 'C:\Program Files (x86)\cloudflared\cloudflared.exe',
  [string] $TunnelName = 'jarvis-vonage',
  [string] $VoiceHost = 'voice.yorkiebrown.uk',
  [string] $JarvisHost = 'jarvis.yorkiebrown.uk',
  [int] $VoicePort = 3339,
  [int] $JarvisPort = 5173,
  [switch] $RouteDns
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $Cloudflared)) {
  Write-Error "cloudflared not found: $Cloudflared`nInstall: winget install Cloudflare.cloudflared"
}

$dir = Join-Path $env:USERPROFILE '.cloudflared'
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$cert = Join-Path $dir 'cert.pem'
if (-not (Test-Path $cert)) {
  Write-Error @"
Missing origin certificate: $cert

Run this once (browser will open — sign in to Cloudflare and pick your team):

  & `"$Cloudflared`" tunnel login

Then run this script again.
"@
}

function Get-TunnelJson {
  # Use cmd so cloudflared stderr (e.g. version warnings) does not become PowerShell errors
  $raw = cmd /c "`"$Cloudflared`" tunnel list --output json 2>nul"
  if ([string]::IsNullOrWhiteSpace($raw) -or $raw.Trim() -eq 'null') { return @() }
  $parsed = $raw | ConvertFrom-Json
  if ($null -eq $parsed) { return @() }
  if ($parsed -is [array]) { return $parsed }
  return @($parsed)
}

$existing = Get-TunnelJson
$match = $existing | Where-Object { $_.name -eq $TunnelName }
if (-not $match) {
  Write-Host "Creating tunnel '$TunnelName'..."
  $createOut = cmd /c "`"$Cloudflared`" tunnel create $TunnelName 2>nul"
  if ($LASTEXITCODE -ne 0 -and $createOut) { Write-Host $createOut }
  $existing = Get-TunnelJson
  $match = $existing | Where-Object { $_.name -eq $TunnelName }
  if (-not $match) { Write-Error "Tunnel '$TunnelName' not found after create." }
}

$tunnelId = $match.id
$credName = "$tunnelId.json"
$credPath = Join-Path $dir $credName
if (-not (Test-Path $credPath)) {
  Write-Error "Credentials file missing: $credPath`nRe-run tunnel create or check Cloudflare dashboard."
}

$configPath = Join-Path $dir 'config.yml'
$credForward = $credPath.Replace('\', '/')

$content = @"
# Jarvis + Vonage — generated by scripts/setup-cloudflared-jarvis-vonage-tunnel.ps1
# Run: & `"$Cloudflared`" tunnel run $TunnelName

tunnel: $tunnelId
credentials-file: $credForward
edge-ip-version: "4"
protocol: http2

ingress:
  - hostname: $VoiceHost
    service: http://127.0.0.1:$VoicePort
  - hostname: $JarvisHost
    service: http://127.0.0.1:$JarvisPort
  - service: http_status:404
"@

Set-Content -Path $configPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Wrote: $configPath"
Write-Host "Tunnel: $TunnelName  (UUID: $tunnelId)"
Write-Host ""

if ($RouteDns) {
  Write-Host "Creating DNS routes (Cloudflare)..."
  & $Cloudflared tunnel route dns $TunnelName $VoiceHost
  & $Cloudflared tunnel route dns $TunnelName $JarvisHost
  Write-Host "DNS routes requested. Check dashboard if records already existed."
} else {
  Write-Host 'Next (DNS - skip if you already routed these hostnames):'
  Write-Host ('  "{0}" tunnel route dns {1} {2}' -f $Cloudflared, $TunnelName, $VoiceHost)
  Write-Host ('  "{0}" tunnel route dns {1} {2}' -f $Cloudflared, $TunnelName, $JarvisHost)
}

Write-Host ''
Write-Host 'Start tunnel (leave running):'
Write-Host ('  "{0}" tunnel run {1}' -f $Cloudflared, $TunnelName)
Write-Host ''
Write-Host 'Then start the app (another terminal): npm run dev'
Write-Host ('Vonage webhooks: https://{0}/api/vonage/webhook/answer (and /event, /inbound-sms)' -f $JarvisHost)
Write-Host ''
