#Requires -Version 5.1
<#
  DEPRECATED for Vonage: this script writes a single-port ingress (wrong for voice + webhooks).

  Use instead:
    .\scripts\setup-cloudflared-jarvis-vonage-tunnel.ps1
  (voice.yorkiebrown.uk -> 3339, jarvis.yorkiebrown.uk -> 5173)

  ---
  Legacy: one hostname -> one local port (after `cloudflared tunnel login`).

  Usage (from repo root, in PowerShell):
    .\scripts\setup-cloudflared-jarvis-vonage.ps1
    .\scripts\setup-cloudflared-jarvis-vonage.ps1 -LocalPort 3339

  Prerequisite: run once interactively:
    & "C:\Program Files (x86)\cloudflared\cloudflared.exe" tunnel login
#>
param(
  [int] $LocalPort = 5173
)

$ErrorActionPreference = 'Stop'
$cf = 'C:\Program Files (x86)\cloudflared\cloudflared.exe'
if (-not (Test-Path $cf)) {
  Write-Error "cloudflared not found at $cf. Install: winget install Cloudflare.cloudflared"
}

$dir = Join-Path $env:USERPROFILE '.cloudflared'
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$cert = Join-Path $dir 'cert.pem'
if (-not (Test-Path $cert)) {
  Write-Error @"
Missing $cert — run tunnel login first (browser will open):

  & `"$cf`" tunnel login

Then re-run this script.
"@
}

$tunnelName = 'jarvis-vonage'
$existing = & $cf tunnel list --output json 2>$null | ConvertFrom-Json
$id = $null
if ($existing) {
  $match = $existing | Where-Object { $_.name -eq $tunnelName }
  if ($match) { $id = $match.id }
}
if (-not $id) {
  Write-Host "Creating tunnel '$tunnelName'..."
  & $cf tunnel create $tunnelName
  $existing = & $cf tunnel list --output json | ConvertFrom-Json
  $match = $existing | Where-Object { $_.name -eq $tunnelName }
  if (-not $match) { Write-Error "Tunnel '$tunnelName' not found after create." }
  $id = $match.id
}

$credName = "$id.json"
$credPath = Join-Path $dir $credName
if (-not (Test-Path $credPath)) {
  Write-Warning "Expected credentials file missing: $credPath — check tunnel create output."
}

$configPath = Join-Path $dir 'config.yml'
$ingress = "http://127.0.0.1:$LocalPort"
$content = @"
# Jarvis — Cloudflare Tunnel (generated by scripts/setup-cloudflared-jarvis-vonage.ps1)
# Run: cloudflared tunnel run jarvis-vonage
# Route DNS (optional): cloudflared tunnel route dns jarvis-vonage YOUR_SUBDOMAIN.yourdomain.com

tunnel: $id
credentials-file: $($credPath.Replace('\', '/'))

ingress:
  - service: $ingress
"@

Set-Content -Path $configPath -Value $content -Encoding UTF8
Write-Host "Wrote $configPath"
Write-Host "Tunnel ID: $id"
Write-Host "Next: cloudflared tunnel route dns jarvis-vonage <hostname>   (optional)"
Write-Host "Then: cloudflared tunnel run jarvis-vonage"
